indexmenu_n_6

== AIS/Radar

=== Radar Overlay Plugins:

Overlay the Radar picture of Garmin or Navico on OpenCPN

*link:ais_radar/radar.html[Radar_pi]* +
The newest and best plugin. Updated to replace GRadar, GxRadar, Navico
(new)3G, 4G, Halo. New Features. Opencpn 5.0 Required.

*link:ais_radar/garmin_radar.html[Garmin Radar]* +
The GRadar plugin works with modern Garmin (Ethernet capable) radar
scanners only. OpenCPN v4.8.4-4.8.8 required.

*link:ais_radar/br24_radar.html[BR24/3G/4G Radar]* +
The Navico broadband plugin will work with a Simrad, Lowrance or B&G
broadband scanner. All three models – BR24, 3G and 4G – are supported
with multiple screens. Version 2.1 is a major upgrade. OpenCPN
v4.8.4-4.8.8 required.

*link:ais_radar/br24_radar/debugging.html[Radar Debugging]* +
Assistance in debugging Navico connections.

=== AIS Plugins

*link:ais_radar/ais_radar_display.html[AIS Radar]* +
Implements a radar-like display for AIS targets. See
https://web.archive.org/web/20160401090244/http://opencpn.org/ocpn/Plugins_external_other[Other
Plugins.] Simple plugin no documentation.

*link:ais_radar/rtlsdr_usb.html[RtlSdr USB] AIS* +
Use a low-cost USB DVB-T (digital TV) receiver to receive AIS messages
from ships.
