indexmenu_n_7

== Charts

*link:../charts/chart_downloader_tab.html[Chart Downloader]* (Plugin
Included in Program download) +
Download, install and keep up to date the navigational charts provided
by various free governmental sources worldwide directly from within
OpenCPN's Toolbox. Supports both the raster and vector charts for the US
waters provided by the NOAA, official raster navigational charts
published by Argentina, Brasil and New Zealand (covering also huge areas
of the Pacific ocean) as well as electronic charts of the inland
waterways of the USA and more than a dozen European Union countries. +
 +
*link:charts/s63_vector_charts.html[s63_vector_charts]* (o-charts) +
A plugin that makes it possible to display standard commercial charts. +
This plugin has a totally different display format and is integrated in
the main program. +
See http://o-charts.org/shop/index.php[O-Charts] S-63 Vector charts for
OpenCPN which has a link to VAR
http://www.chartworld.com/shop/off_enc[Chartworld for ENC charts.] +
 +
*link:charts/oesenc.html[oesenc]* (o-charts) +
A Plugin for Vector charts licensed from official bodies for OpenCPN,
especially for waters outside of the US. This is an encrypted format
with its own plug-in, the oeSENC plug-in. Special and exclusive for
OCPN. Derived from S-57, but already in an easy to digest format for
OCPN (ocpn encrypted SENC). These charts are distributed through
http://o-charts.org/shop/index.php[o-charts] at very competitive prices
for vector charts of this quality. Germany, Belgium, the Netherlands,
the British Isles, France, Iceland, Spain, Norway, Sweden, Crotia,
Finland, Poland, Estonia, Italy, Denmark, Australia or Canada are
available. Portugal shall be added. +
Just visit http://www.o-charts.org[www.o-charts.org] to get an overview
about the actual coverage.

*link:charts/oernc.html[oeRNC Charts]* (o-charts) +
_The plug-in for_ *_oeRNC_* give access to raster charts are sourced
from editors covering sailing regions where vector charts are not
available or are lower quality than the alternative raster sources. +
Leaving it up to the sailor to decide which chart set suites his
requirements. We want to serve sailors preferring raster over vector as
well. +
_oeRNC_ charts are licensed and encrypted for OpenCPN. +
The first sets are covering the Bahamas (Explorer Charts), The Eastern
Caribbean, Adriatic&Ionean Sea and The Aegean& Eastern med. The latter
three are Imray charts. For information about the latest coverage visit
http://www.o-charts.org[www.o-charts.org]

*link:charts/fugawi.html[Fugawi Charts]* +
http://Fugawi.com[Fugawi.com] is a portal offering raster charts from
different editors in a common uniform format. +
Chart sets from sources like for example NV, Delius-Klasing, Solteknik,
BlueLatitude or Explorer Charts and others are found here under one
roof. +
The FugawiChart-PlugIn gives access to these charts. +
Fugawi has stopped licensing charts from December 1st, 2018 on and will
maintain support until November, 2019.

*link:charts/nv_charts.html[nv_charts]* +
The NVC charts are purchased only from the German publisher NV Verlag
This plugin runs
https://web.archive.org/web/20160401090244/http://us.nvcharts.com/[NVC
Charts]. +
 +
*link:charts/bsb4_charts.html[bsb4_charts]* +
A plugin which makes it possible to use MAPTEC encrypted BSB4 charts for
which encryption certificates have been purchased and registered on the
computer running OpenCPN. +
 +
*link:charts/vfkaps.html[vfKaps -VentureFather Satellite Kap Charts]* +
A plugin which makes it easy to create google earth, bing and nokia kap
files. In some areas of the world a satellite chart is more accurate
than even the official chart. This plugin allows satellite charts from
Google, Bing or Nokia to be downloaded via the VentureFarther server.

=== Interface Tools

*link:charts/rotationctrl.html[RotationCtrl]* +
Controls to rotate the charts in various ways. North up, South up,
Course up, Heading up, Route up, Wind up, Tilt down, Tilt up. Rotate
CCW, Rotate CW.

*link:charts/chartscale.html[Chartscale]* +
Slider to change the chartscale. Useful utility.

*link:charts/objsearch.html[Object Search]* +
Allows search of named objects on S-57 and CM93 vector charts.

*link:charts/projections.html[Projections]* +
Utility to project the charts in many alternative projections configured
by the user. Right-click shows “Projections” with user selection for
Mercator, Orthographic, Polar, Stereographic, Genomonic, ane
Equirectangular. These projections may be useful for a more accurate
interpretation of navigational data. Mercator is especially skewed at
high lattitudes. Requires opengl.

=== Chart Sources

*_http://www.visitmyharbour.com/charts-for-opencpn.asp[VisitMyHarbor]_* +
Has charts for UK, Ireland, Near Contenant, Iberia.
https://www.visitmyharbour.com/charts-for-opencpn.asp[VisitmyHarbor] +
 +
*_Other Sources_* +
See OpenCPN User Manual for other
https://opencpn.org/ocpn/Basic_charts_chart-sources[Chart Sources].
