indexmenu_n_9

== Navigation

*link:navigation/squiddio.html[sQuiddio]* +
Global user-sourced and user-maintained repository of sailing
destinations (marinas, anchorages, yacht clubs, docks, fuel stations
etc.) available as waypoints in OpenCPN through a plugin.

*link:navigation/googleearth.html[Google Earth]* +
Links a Google Earth satellite image to the area of chart being
explored.

*link:navigation/celestial_navigation.html[Celestial Navigation]* +
Plugin to record Sextant Sights and show Circles of Position to obtain a
Fix

*link:navigation/route_great_circle.html[Great Circle Route]* +
A short introduction to to the Great Circle part of the Route Plugin.
Route Plotting, Great Circle routes, Limited Circle Routes and Rhumb
lines.

*link:navigation/dead_reckoning.html[DR Dead Reckoning]* +
Add DR positions to a GPX file exported from OpenCPN

*link:navigation/otcurrent.html[oTCurrent]* +
Display tidal current arrows for times other than the present

*link:navigation/photo_layer.html[PhotoLayer]* +
Geotiff files can be overlayed on the chart. Transparency can be
adjusted.

*link:navigation/ge2kap.html[GE2KAP]* +
Use GE2Kap to create Kap files which can be overlaid on Charts.
(Companion software, not a plugin)
