indexmenu_n_11

== Weather

*link:weather/iacfleet.html[IACfleet]* +
IAC Fleet Code visualizes the encoded data issued as part of the weather
bulletins. The IAC Fleet Code provides size effective encoded synoptic
charts for several areas of the world, especially useful with slow and
limited connection to the Internet. Coverage areas:

* South Pacific weather issued by Fiji Meteorologica Service in Nadi and
available from Saildocs
* Weather over Brazil and adjacent parts of Pacific and Atlantic oceans,
including direct download of the data from the Internet
* Weather analysis and 24 hour forecast for North Atlantic and Europe
issued by NOAA, including direct download of the data from the Internet.

*link:weather/weatherfax.html[Weatherfax]* +
Read weather fax encoded data as audio or image and Overlay on top of
charts.

*link:weather/weather_routing.html[Weather Routing]* +
Establish an estimate of optimal weather routing using Grib Plugin and
Climatology. Establish “Boundaries” using Ocpn_draw.

*link:weather/climatology.html[Climatology]* +
Manage and view monthly gridded climate data.

*link:included_plugins/grib_weather.html[Grib Weather]* (Included
Plugin) +
Plugin to display Grib weather data files. Included in the OpenCPN
installation.
