indexmenu_n_2

== Radar_pi

=== Radar_pi v5.0 - Replaces BR24, Gradar, GXRadar Plugins

Radar PI replaces GRradar, GXRadar, and BR24 Radar plugins for OpenCPN
ver 5.0 and up. This plugin overlays the radar picture on OpenCPN. A
versatile plugin that can be easily adapted to most broadband radars. We
will leave this documentation in place for about 4 months for users of
v4.8.8 and the dedicated Garmin plugin.

Plugin by Hans, Kees Verruijt, Douwe Fokkema, Dave Register and Håkan
Svensson

* Binary Release:
https://opencpn.org/OpenCPN/plugins/radarPI.html[Radar_pi 5.0 for
Windows & Mac, OpenCPN v5.0]
* Forum:
http://www.cruisersforum.com/forums/f134/radar-plugin-v5-0-0-released-216057.html[Radar
plugin v5.0.0 released]
* Github:
https://github.com/opencpn-radar-pi/radar_pi/blob/master/README.md[Readme
for Building]
* Github Repository:
https://github.com/opencpn-radar-pi/radar_pi[OpenCPN Radar_pi]
* Radar_pi Wiki:
https://github.com/opencpn-radar-pi/radar_pi/wiki[Radar_pi Wiki]

The following radar scanners are supported by *Radar_pi* for OCPN
version 5.0 and later:

* Garmin HD and xHD radar support.
* Navico 4G
* Navico HALO (20, 20+, 24, 4, 6, 8) support
* Navico 3G support. (Some 3G firmware before Oct 2014 will require set
up as a BR24.)
* Navico BR24 support.

Manual for this plugin will be found here:
https://github.com/opencpn-radar-pi/radar_pi/wiki[Radar_pi Wiki]

http://www.cruisersforum.com/forums/f134/radar-plugin-v5-0-0-released-216057.html#post2907038[Radar_pi
5.0 Running] BCN writes: “Guys, this plug-in is really fantastic. Radar
(Navico 3G) unboxed, supplied cable attached, Ethernet plug-in goes into
the PC, power-supply connected, PI enabled, PI requests type of
equipment, and that's it. Running. What a pleasure! Thanks! Hubert ”

=== Troubleshooting Verbose Logging

In the OpenCPN.ini/conf file, make

[source,code]
----
 VerboseLog=13 (transmit+receive+verbose)
----

Run OpenCPN with radar until crash, and put the OpenCPN.log file here on
the forum
http://www.cruisersforum.com/forums/showthread.php?p=2908898#post2908898[Radar
plugin v5.0.0 released]

=== Troubleshooting, Menu Display problems

Description: +
4g radar, if radar A is selected, radar A is seen. If radar A + B is
selected, both are seen. IP Addresses can be seen, however the menu
panel for Start/Stop and adjustment does not appear on the screen. Maybe
it's a problem with opengl? How to fix the problem?

Self-fixed: +
The problem was in the wifi network settings. Wifi was in 'private'
mode, when changed 'public' mode it works perfectly over wifi.
