site:
  title: TideFinder Plugin Documentation

content:
  sources:
  - url: https://github.com/Rasbats/TF.git
    branches: master
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    edit_url: false
  - url: ../
    branches: HEAD
    start_path: docs/

ui:
  output_dir: assets
  bundle:
    url: https://github.com/Rasbats/TF/files/6096963/ui-bundle.zip
    snapshot: true
    

output:
  clean: true
  

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
